[versions]
accompanistDrawablepainter = "0.37.0"
activityCompose = "1.10.0"
agp = "8.5.2"
biometric = "1.4.0-alpha02"
cloudy = "0.2.4"
composeBom = "2025.01.01"
composeVideo = "1.2.0"
constraintlayoutCompose = "1.1.0"
core = "0.10.0"
coreSplashscreen = "1.0.1"
gson = "2.10.1"
jasypt = "1.9.3"
kotlin = "2.1.0"
coreKtx = "1.15.0"
appcompat = "1.7.0"
kotlinxSerializationJson = "1.7.3"
material = "1.12.0"
constraintlayout = "2.2.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
media3Exoplayer = "1.5.1"
media3Session = "1.5.1"
media3Ui = "1.5.1"
navigationCompose = "2.8.6"
navigationFragmentKtx = "2.8.6"
navigationUiKtx = "2.8.6"
exifinterface = "1.3.7"
ossLicensesPlugin = "0.10.6"
playServicesOssLicenses = "17.1.0"
shimmer = "0.1.0"
materialCompose = "1.3.1"
material-extended = "1.7.7"
uiViewbinding = "1.7.7"
jetbrainsKotlinJvm = "2.1.0"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistDrawablepainter" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "materialCompose" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Session" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
cloudy = { module = "com.github.skydoves:cloudy", version.ref = "cloudy" }
compose-video = { module = "io.sanghun:compose-video", version.ref = "composeVideo" }
core = { module = "me.jahnen.libaums:core", version.ref = "core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
jasypt = { module = "org.jasypt:jasypt", version.ref = "jasypt" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
androidx-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "uiViewbinding" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
