[versions]
accompanistDrawablepainter = "0.37.2"
activityCompose = "1.10.1"
agp = "8.5.2"
biometric = "1.4.0-alpha02"
cloudy = "0.2.6"
composeBom = "2025.02.00"
composeVideo = "1.2.0"
constraintlayoutCompose = "1.1.1"
core = "0.10.0"
coreSplashscreen = "1.0.1"
gson = "2.12.1"
kotlin = "2.1.10"
coreKtx = "1.15.0"
appcompat = "1.7.0"
kotlinxSerializationJson = "1.8.0"
material = "1.12.0"
constraintlayout = "2.2.1"
navigationCompose = "2.8.8"
navigationFragmentKtx = "2.8.8"
navigationUiKtx = "2.8.8"
exifinterface = "1.4.0"
ossLicensesPlugin = "0.10.6"
playServicesOssLicenses = "17.1.0"
materialCompose = "1.3.1"
material-extended = "1.7.8"
uiViewbinding = "1.7.8"
jetbrainsKotlinJvm = "2.1.10"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistDrawablepainter" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "materialCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
cloudy = { module = "com.github.skydoves:cloudy", version.ref = "cloudy" }
compose-video = { module = "io.sanghun:compose-video", version.ref = "composeVideo" }
core = { module = "me.jahnen.libaums:core", version.ref = "core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
androidx-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "uiViewbinding" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
