name: Build

on:
#  push:
#    branches: [ "main" ]
#    paths:
#      - "**.gradle.kts"
#      - "iosInputs"
#      - "**.kt"
#      - "gradle/**"
#      - "gradle.properties"
#      - "keys/**"
#      - "**/src/**"
#      - "!**/src/iosMain"
#      - "**.pro"
#      - "iosApp/**"
#      - "iosInputs/**"
  schedule:
    - cron: '30 13 * * *'  # Run at 16:30 MSK every day
  workflow_dispatch:
    inputs:
      force_build:
        type: boolean
        description: "Force build"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.any_changed == 'true' || inputs.force_build }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for comparing changes
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            source:
              - '**.gradle.kts'
              - '**.kt'
              - 'gradle/**'
              - 'gradle.properties'
              - 'keys/**'
              - '**/src/**'
              - '**.pro'

  build-android:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    name: "Build"

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set up keystore
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "storePassword=$STORE_PASSWORD" > keystore.properties
        echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
    - name: Build with Gradle
      run: ./gradlew assembleRelease --no-daemon
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Android
        path: ./app/build/outputs/apk/release/app-release.apk
